import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Shield, Search, AlertTriangle, CheckCircle, TrendingUp, Clock, BarChart3, RefreshCw, Eye, EyeOff, Zap, FileText } from 'lucide-react'

export default function ShadowbanHub() {
  const [username, setUsername] = useState('')
  const [loading, setLoading] = useState(false)
  const [scanType, setScanType] = useState('fast')
  const [result, setResult] = useState(null)

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-10 md:py-16">
      <div className="mb-10"><div className="flex items-center gap-3 mb-3"><div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-cyan-500 rounded-xl flex items-center justify-center"><Shield size={20} className="text-white" /></div><div><h1 className="text-2xl md:text-3xl font-bold">Shadowban Hub</h1><p className="text-sm text-[#71767b]">Audit kesehatan akun X secara realtime</p></div></div></div>
      <div className="glass rounded-2xl p-6 md:p-8 mb-8"><h2 className="font-semibold text-white mb-4 flex items-center gap-2"><Search size={18} className="text-[#1d9bf0]" />Mulai Audit</h2>
        <div className="flex flex-col sm:flex-row gap-3 mb-4"><div className="relative flex-1"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-[#71767b]">@</span><input type="text" placeholder="username X" value={username} onChange={(e) => setUsername(e.target.value.replace(/@/g, ''))} className="w-full bg-[#0a0a0a] border border-[#2a2a2a] rounded-lg pl-8 pr-4 py-3 text-sm text-white focus:outline-none focus:border-[#1d9bf0] transition-colors" onKeyDown={(e) => e.key === 'Enter' && (async () => { if (!username.trim()) return; setLoading(true); setResult(null); await new Promise(r => setTimeout(r, scanType === 'deep' ? 3500 : 1500)); setResult({username: username.replace(/@/g, ''), timestamp: new Date().toLocaleString('id-ID'), scanType, checks: { searchBan: Math.random()>0.65, suggestionBan: Math.random()>0.7, ghostBan: Math.random()>0.8, visibilityScore: Math.floor(Math.random()*35+55) }, recentFlags: [{type:'Search Visibility',value:Math.floor(Math.random()*30+65)},{type:'Reply Visibility',value:Math.floor(Math.random()*30+60)},{type:'Engagement Rate',value:Math.floor(Math.random()*10+2)},{type:'Grok Indexing',value:Math.floor(Math.random()*40+55)}]}); setLoading(false) })()} /></div><button onClick={async () => { if (!username.trim()) return; setLoading(true); setResult(null); await new Promise(r => setTimeout(r, scanType === 'deep' ? 3500 : 1500)); setResult({username: username.replace(/@/g, ''), timestamp: new Date().toLocaleString('id-ID'), scanType, checks: { searchBan: Math.random()>0.65, suggestionBan: Math.random()>0.7, ghostBan: Math.random()>0.8, visibilityScore: Math.floor(Math.random()*35+55) }, recentFlags: [{type:'Search Visibility',value:Math.floor(Math.random()*30+65)},{type:'Reply Visibility',value:Math.floor(Math.random()*30+60)},{type:'Engagement Rate',value:Math.floor(Math.random()*10+2)},{type:'Grok Indexing',value:Math.floor(Math.random()*40+55)}]}); setLoading(false) }} disabled={loading || !username.trim()} className="bg-[#1d9bf0] hover:bg-[#1a8cd8] disabled:opacity-50 text-white px-6 py-3 rounded-lg font-medium flex items-center justify-center gap-2 transition-all">{loading ? <RefreshCw size={16} className="animate-spin" /> : <Search size={16} />}Scan Sekarang</button></div>
        <div className="flex gap-2">{[{ value: 'fast', label: 'Fast Scan', desc: '~3 detik', icon: Zap },{ value: 'deep', label: 'Deep Scan', desc: '~8 detik', icon: Shield }].map(({ value, label, desc, icon: Icon }) => (<button key={value} onClick={() => setScanType(value)} className={`flex-1 sm:flex-none px-4 py-2.5 rounded-lg text-sm font-medium transition-all flex items-center gap-2 ${scanType === value ? 'bg-[#1d9bf0]/10 border border-[#1d9bf0]/30 text-[#1d9bf0]' : 'bg-[#0a0a0a] border border-[#2a2a2a] text-[#71767b] hover:text-white'}`}><Icon size={14} /><span>{label}</span><span className="text-[10px] opacity-60 hidden sm:inline">{desc}</span></button>))}</div></div>
      {loading && (<div className="glass rounded-2xl p-12 text-center"><RefreshCw size={40} className="animate-spin mx-auto mb-4 text-[#1d9bf0]" /><p className="text-[#71767b]">{scanType === 'deep' ? 'Melakukan deep scan...' : 'Memindai akun...'}</p></div>)}
      {result && (<div className="space-y-6"><div className="glass rounded-2xl p-6 md:p-8"><div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6"><div><h3 className="font-bold text-xl flex items-center gap-2">@{result.username}<span className="text-xs bg-[#1d9bf0]/10 text-[#1d9bf0] px-2 py-0.5 rounded-full">{result.scanType === 'deep' ? 'Deep Scan' : 'Fast Scan'}</span></h3><p className="text-xs text-[#555] mt-1 flex items-center gap-1"><Clock size={12} /> {result.timestamp}</p></div><div className="text-center md:text-right"><div className="text-4xl font-extrabold gradient-text">{result.checks.visibilityScore}</div><p className="text-xs text-[#71767b]">Visibility Score / 100</p></div></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4">{[{ key: 'searchBan', label: 'Search Ban', icon: Search, detail: 'Akun muncul di hasil pencarian X' },{ key: 'suggestionBan', label: 'Suggestion Ban', icon: Eye, detail: 'Akun muncul di suggestion/autocomplete' },{ key: 'ghostBan', label: 'Ghost Ban', icon: EyeOff, detail: 'Reply/tweet terlihat oleh non-followers' }].map(({ key, label, icon: Icon, detail }) => { const check = result.checks[key]; const statusColor = check ? 'text-[#f4212e]' : 'text-[#00ba7c]'; const statusBg = check ? 'bg-[#f4212e]/10' : 'bg-[#00ba7c]/10'; return (<div key={key} className={`rounded-xl p-4 ${statusBg} border border-transparent ${check ? 'border-[#f4212e]/20' : 'border-[#00ba7c]/20'}`}><div className="flex items-center gap-2 mb-2"><Icon size={16} className={statusColor} /><span className={`font-semibold text-sm ${statusColor}`}>{label}</span></div><span className={`text-xs font-medium ${statusColor}`}>{check ? 'Terdeteksi' : 'Aman'}</span><p className="text-xs text-[#71767b] mt-1">{detail}</p></div>)})}</div></div><div className="glass rounded-2xl p-6 md:p-8"><h3 className="font-bold text-white mb-4 flex items-center gap-2"><BarChart3 size={18} className="text-[#1d9bf0]" />Metrik Visibilitas</h3><div className="space-y-4">{result.recentFlags.map(({ type, value }) => (<div key={type}><div className="flex items-center justify-between mb-1.5"><span className="text-sm text-[#a0a0a0]">{type}</span><span className="text-sm font-medium text-white">{value}%</span></div><div className="w-full h-2 bg-[#0a0a0a] rounded-full overflow-hidden"><div className={`h-full rounded-full transition-all duration-1000 ${value > 70 ? 'bg-[#00ba7c]' : value > 40 ? 'bg-[#ffd400]' : 'bg-[#f4212e]'}`} style={{ width: `${value}%` }} /></div></div>))}</div></div></div>)}
      {!result && !loading && (<div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-8">{[{ icon: Shield, title: '4 Lapisan Audit', desc: 'Fast scan, deep scan, search ban, dan suggestion ban.' },{ icon: BarChart3, title: 'Laporan 7 Hari', desc: 'Pantau tren shadowban akunmu mingguan.' },{ icon: Eye, title: 'Moderasi Post', desc: 'Cek apakah postinganmu disembunyikan.' },{ icon: TrendingUp, title: 'Recovery Path', desc: 'Dapatkan langkah konkret untuk pulihkan visibility.' }].map(({ icon: Icon, title, desc }) => (<div key={title} className="glass rounded-xl p-5 card-hover"><Icon size={20} className="text-[#1d9bf0] mb-3" /><h4 className="font-semibold text-white mb-1">{title}</h4><p className="text-sm text-[#71767b]">{desc}</p></div>))}</div>)}
    </div>
  )
}